spring.application.name=api

##?createDatabaseIfNotExist=true

spring.datasource.url=jdbc:mysql://localhost:3306/med_api
spring.datasource.username=${USER_MYSQL}
spring.datasource.password=${PASSWORD_MYSQL}

